services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - my_network
  
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    depends_on:
      - traefik
    command:
      - "http"
      - "traefik:80"
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    networks:
      - my_network


  # --- DATABASES (Sem alterações) ---
  db:
    image: postgres:16
    container_name: auth-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth_steam_shopee
    ports:
      - "5454:5432"
    volumes:
      - postgres_auth_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-users:
    image: postgres:16
    container_name: users-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_users_steam_shopee
    ports:
      - "5455:5432"
    volumes:
      - postgres_users_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-games:
    image: postgres:16
    container_name: games-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_games_steam_shopee
    ports:
      - "5456:5432"
    volumes:
      - postgres_games_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-comments:
    image: postgres:16
    container_name: comments-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_comments_steam_shopee
    ports:
      - "5457:5432"
    volumes:
      - postgres_comments_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  
  
  # --- SERVIÇOS NESTJS ---

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: authentication
    container_name: authentication
    restart: always
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      DATABASE_AUTH_URL: "postgresql://postgres:postgres@db:5432/db_auth_steam_shopee?schema=public"
    depends_on:
      - db
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/authentication`)"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"

  users-service:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: users
    container_name: users
    restart: always
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      DATABASE_USERS_URL: "postgresql://postgres:postgres@db-users:5432/db_users_steam_shopee?schema=public"
    depends_on:
      - db-users
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/api/v1/users`)"
      - "traefik.http.services.users-service.loadbalancer.server.port=3002"

  games-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: games
    container_name: games
    restart: always
    ports:
      - "3003:3003"
      - "50053:50053"
    environment:
      DATABASE_GAMES_URL: "postgresql://postgres:postgres@db-games:5432/db_games_steam_shopee?schema=public"
    depends_on:
      - db-games
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.games.rule=PathPrefix(`/api/v1/games`)"
      - "traefik.http.services.games-service.loadbalancer.server.port=3003"
  
  comments-service:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: comments
    container_name: comments
    restart: always
    ports:
      - "3004:3004"
      - "50055:50055"
    environment:
      DATABASE_COMMENTS_URL: "postgresql://postgres:postgres@db-comments:5432/db_comments_steam_shopee?schema=public"
    depends_on:
      - db-comments
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comments.rule=PathPrefix(`/api/v1/comments`)"
      - "traefik.http.services.comments-service.loadbalancer.server.port=3004"
  
volumes:
  postgres_auth_steam_shopee_data:
  postgres_users_steam_shopee_data:
  postgres_games_steam_shopee_data:
  postgres_comments_steam_shopee_data:

networks:
  my_network:
    driver: bridge