services:


  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command: 
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Configuração do dashboard API
      - --api.dashboard=true
      # Redirecionamento Global HTTP -> HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Configuração LetsEncrypt
      - --certificatesresolvers.le.acme.email=pedroantonio5735@gmail.com 
      - --certificatesresolvers.le.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Porta do dashboard do Traefik
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.pedrooaj.cloud`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=le"


  # PostgreSQL Databases da Steam Shopee
  db:
    image: postgres:16
    container_name: auth-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth_steam_shopee
    ports:
      - "5454:5432"
    volumes:
      - postgres_auth_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-users:
    image: postgres:16
    container_name: users-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_users_steam_shopee
    ports:
      - "5455:5432"
    volumes:
      - postgres_users_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-games:
    image: postgres:16
    container_name: games-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_games_steam_shopee
    ports:
      - "5456:5432"
    volumes:
      - postgres_games_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  db-comments:
    image: postgres:16
    container_name: comments-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_comments_steam_shopee
    ports:
      - "5457:5432"
    volumes:
      - postgres_comments_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network
  
  
  # Serviços em NEST JS da Steam Shopee
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: authentication
    container_name: authentication
    restart: always
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      DATABASE_AUTH_URL: "postgresql://postgres:postgres@db:5432/db_auth_steam_shopee?schema=public"
    depends_on:
      - db
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      # Regra de roteamento: usa subdomínio para HTTPS
      - "traefik.http.routers.auth-service.rule=Host(`auth.pedrooaj.cloud`)" # ➡️ MUDAR
      # Usa o entrypoint seguro 443
      - "traefik.http.routers.auth-service.entrypoints=websecure"
      # Aplica o Resolvedor de Certificados 'le'
      - "traefik.http.routers.auth-service.tls.certresolver=le"
      # Porta interna do serviço
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"
  users-service:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: users
    container_name: users
    restart: always
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      DATABASE_USERS_URL: "postgresql://postgres:postgres@db-users:5432/db_users_steam_shopee?schema=public"
    depends_on:
      - db-users
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-service.rule=Host(`users.pedrooaj.cloud`)" # ➡️ MUDAR
      - "traefik.http.routers.users-service.entrypoints=websecure"
      - "traefik.http.routers.users-service.tls.certresolver=le"
      - "traefik.http.services.users-service.loadbalancer.server.port=3002"

  games-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: games
    container_name: games
    restart: always
    ports:
      - "3003:3003"
      - "50053:50053"
    environment:
      DATABASE_GAMES_URL: "postgresql://postgres:postgres@db-games:5432/db_games_steam_shopee?schema=public"
    depends_on:
      - db-games
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.games-service.rule=Host(`games.pedrooaj.cloud`)" # ➡️ MUDAR
      - "traefik.http.routers.games-service.entrypoints=websecure"
      - "traefik.http.routers.games-service.tls.certresolver=le"
      - "traefik.http.services.games-service.loadbalancer.server.port=3003"
  
  comments-service:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: comments
    container_name: comments
    restart: always
    ports:
      - "3004:3004"
      - "50055:50055"
    environment:
      DATABASE_COMMENTS_URL: "postgresql://postgres:postgres@db-comments:5432/db_comments_steam_shopee?schema=public"
    depends_on:
      - db-comments
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comments-service.rule=Host(`comments.pedrooaj.cloud`)" # ➡️ MUDAR
      - "traefik.http.routers.comments-service.entrypoints=websecure"
      - "traefik.http.routers.comments-service.tls.certresolver=le"
      - "traefik.http.services.comments-service.loadbalancer.server.port=3004"
  
volumes:
  postgres_auth_steam_shopee_data:
  postgres_users_steam_shopee_data:
  postgres_games_steam_shopee_data:
  postgres_comments_steam_shopee_data:

networks:
  my_network:
    driver: bridge