services:
  db:
    image: postgres:16
    container_name: auth-db-steam-shopee-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth_steam_shopee
    ports:
      - "5454:5432"
    volumes:
      - postgres_auth_steam_shopee_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_auth_steam_shopee_data:

networks:
  my_network:
    driver: bridge